spring:
  application:
    name: biz-service
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/sba?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      minimum-idle: 2
      maximum-pool-size: 10

server:
  port: 8090

    # ===================================================================
  #  properties.
  # ===================================================================
sba:
  frontend:
    url: http://localhost:4200

eureka:
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
